services:
  - type: web
    name: ellzizz-app
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_KEY
        value: base64:Gthfl1NEhVn58BAJInK9sX4/WA0w5O0maqwfGZ2n40Y=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
